config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :pokemon_accounts

end

app/models/pokemon_account.rb
class PokemonAccount < ActiveRecord::Base
  require 'poke-api'

  belongs_to :user

  # after_commit :pkmn_api, on: :create

  # def pkmn_api
  #   client = Poke::API::Client.new
  #   client.store_location('Paris')
  #   client.login(self.email, self.encrypted_password, 'google')
  #   puts client.owned_by_team
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :pokemon_account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include HttpAcceptLanguage::AutoLocale

  def asset_exist?(path)
    if Rails.configuration.assets.compile
      Rails.application.precompiled_assets.include? path
    else
      Rails.application.assets_manifest.assets[path].present?
    end
  end
end

app/controllers/pokemon_accounts_controller.rb
class PokemonAccountsController < ApplicationController
  require 'pp'
    before_action :find_account, only: [:show, :edit, :update]
    before_filter :authenticate_user!, only: [:new, :create, :show]

    def index
    end

    def create
      @account = PokemonAccount.new(account_params)
      @account.user_id = current_user.id

      if @account.save
        redirect_to pokemon_account_path(@account)
      else
        render 'new'
      end
    end

    def new
      @account = PokemonAccount.new
    end

    def edit
    end

    def show
      @client = Poke::API::Client.new
      # @client.store_location(@account.adress)
      @client.login(@account.email, @account.password, 'google')
      # # Add RPC calls
      @client.get_player
      @client.get_inventory
      # # You can inspect the client before performing the call
      # puts @client.inspect

      # # Perform your RPC call
      @call = @client.call
      # # A <Poke::API::Response> object is returned and decorated with your request and response in a Hash format
      # # Request
      @inventory = @call.response[:GET_INVENTORY][:inventory_delta][:inventory_items]

      @pokemons = []
      @candies = {}
      @items = {}
      @pokedex = {}
      # # Response
      # puts @call.response.inspect
    end

    def update
      if @account.update(account_params)
        redirect_to pokemon_account_path(@account)
      else
        render 'edit'
      end
    end

    private
      def account_params
        params.require(:pokemon_account).permit(:email, :password, :adress)
      end

      def find_account
        @account = PokemonAccount.find(params[:id])
      end

  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    def pkmn_api
      client = Poke::API::Client.new
      client.store_location(self.adress)
      client.login(self.email, self.encrypted_password, 'google')
      puts client.owned_by_team
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokemongo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
        <img src="<%= image_path("pkball.png") %>"/>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">

        <% if user_signed_in? %>
          <li class="text-center"><%= link_to 'DECONNEXION', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class="text-center"><%= link_to 'CONNEXION', new_user_session_path %></li>
          <li class="text-center"><%= link_to "S'INSCRIRE", new_user_registration_path %></li>
        <% end %>

      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pokemon_account/edit.html.erb
<p>EDIT (form)</p>

app/views/pokemon_account/new.html.erb
<p>NEW (form)</p>

app/views/pokemon_account/show.html.erb
<p>SHOW</p>

app/views/pokemon_accounts/_form.html.erb
<%= simple_form_for @account do |f| %>
  <%= f.input :email, input_html: {maxlength: 50, placeholder:'Mon identifiant Pokemon GO'}, label: 'Identifiant' %>
  <%= f.input :password, placeholder:'Mon mot de passe Pokemon GO', label: 'Mot de Passe' %>
  <%= f.input :adress, placeholder:'Mon adresse actuelle', label: 'Adresse' %>
  <%= f.button :submit, 'Lier mon compte' %>
<% end %>

app/views/pokemon_accounts/edit.html.erb
<p>EDIT (form)</p>

<%= simple_form_for @account do |f| %>
  <%= f.input :email, input_html: {maxlength: 50, placeholder:'Mon identifiant Pokemon GO'}, label: 'Identifiant' %>
  <%= f.input :password, placeholder:'Mon mot de passe Pokemon GO', label: 'Mot de Passe' %>
  <%= f.input :adress, placeholder:'Mon adresse actuelle', label: 'Adresse' %>
  <%= f.button :submit, 'Mettre à jour mon compte' %>
<% end %>

app/views/pokemon_accounts/new.html.erb
<div class="col-xs-6 col-xs-offset-3">
  <h2>Lier mon compte POKEMON GO</h2>
  <% if current_user.pokemon_account.present? %>
  <p>Compte deja lié</p>
  <h3><%= link_to 'Voir mon profil', pokemon_account_path(current_user.pokemon_account.id) %></h3>
  <% else %>
  <%= render 'form' %>
  <% end %>
</div>

app/views/pokemon_accounts/show.html.erb
<div class="text-center">
  <h2 class="text-center">Mon Profil</h2>
  <div class="col-xs-12">
    <img src="<%= asset_path('trainer.png') %>" class="img-responsive center-block"></img>
  <strong>
    <p><%= @call.response[:GET_PLAYER][:player_data][:username]%></p>
    <p><%= @call.response[:GET_PLAYER][:player_data][:avatar][:gender]%></p>
    <p>TEAM <%= @call.response[:GET_PLAYER][:player_data][:team]%></p>
    <br><br>
  </strong>
  </div>



  <h2 class="text-center">Mes Pokemons</h2>

  <% i = 0 %>
    <% @inventory.each do |item| %>
        <% if !item[:inventory_item_data][:pokemon_data].nil? %>

          <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2 height_244">

          <% if item[:inventory_item_data][:pokemon_data][:is_egg] == true %>
            <h3><%= t('EGG') %></h3>
          <img src="<%= asset_path('poke_egg.png') %>" class="img-responsive center-block height_100"></img>
            <h4>Need: <%= item[:inventory_item_data][:pokemon_data][:egg_km_walked_target] %> km</h4>
            <h4>__</h4>
          <% else %>

            <h3><%= t(item[:inventory_item_data][:pokemon_data][:pokemon_id]) %></h3>
            <% if !asset_path(((item[:inventory_item_data][:pokemon_data][:pokemon_id]).to_s) + '.jpg').nil? %>
              <img src="<%= asset_path(((item[:inventory_item_data][:pokemon_data][:pokemon_id]).to_s) + '.jpg') %>" class="img-responsive center-block height_100"></img>
            <% else %>
              <img src="<%= asset_path('pkmn.png') %>" class="img-responsive center-block height_100"></img>
            <% end %>
            <h4>CP: <%= item[:inventory_item_data][:pokemon_data][:cp] %>
            <h4>Stamina: <%= item[:inventory_item_data][:pokemon_data][:stamina] %>
          <% end %>
          </div>
        <% end %>

    <% end %>
    <br><br>
</div>
<br><br>
<% @inventory.each do |item| %>
<% if !item[:inventory_item_data][:pokemon_data].nil? %>
<%= item[:inventory_item_data][:pokemon_data] %>
<% end %>
<% end %>
<br><br>

app/views/welcome/index.html.erb
<div class="text-center">
  <% if user_signed_in? %>
    <% if current_user.pokemon_account.present? %>
      <h3><%= link_to 'Voir mon profil', pokemon_account_path(current_user.pokemon_account.id) %></h3>
    <% else %>
    <h2><%= link_to 'Renseigne tes identifiants POKEMON GO', new_pokemon_account_path %><h2>
    <% end %>
  <% else %>
    <h2>Bienvenue Dresseur</h2>
    <h4>Pour commencer, inscris-toi ou connecte-toi !</h4>
  <% end %>
  <div class="col-xs-6 col-xs-offset-3">
    <img src="<%= asset_path('Pokemon_Go.png') %>" class="img-responsive center-block"></img>
  </div>
</div>